# This is a basic workflow to help you get started with Actions

name: Data Sharing between jobs

# Controls when the workflow will run
on: [push]

jobs:

  job1:
    runs-on: ubuntu-latest
    - shell: bash
      run:
      cal 2022 > calendar.txt
    - name: Upload the cal.txt file
      uses: actions/upload-artifact@v3
      with:
        name: calendar
        path: calendar.txt
      
  job2:
    runs-on: windows-latest

  job3:
    runs-on: macOS-latest
