# This is to understand user defined variables

name: User defined Variable Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
env:
    firstName: Tina
    lastName: Xia


# Read User Defined Variables from environment
jobs:
 windows-job:
  runs-on:
    windows-latest
  steps:
    - name: Display env Variables
      run: echo "Hi ${{env.firstName}}"     #echo is to showing value output in the console
    - name:  Display Last name Variable
      run: echo "Hi ${{env.lastName}}"
    - name: Display Job
      run: echo "${{job}}"
      env:
        job: "Developer"
    
 ubuntu-job:
   runs-on:
      ubuntu-latest
   steps: 
      - name: Display env variables
        run: echo "Hi ${{env.lastName}}"
        
 if-Windows-else:
  runs-on: macos-latest
  steps:
    - name: condition 1
      if: runner.os == 'Windows'
      run: echo "The operation system on the runner is $env:RUNNER_OS."
    - name: condition 2
      if: runner.os != 'Windows'
      run: echo "The operation system on the runner is not Windows, it's $RUNNER_0S."
